<!-- GENERATED by tools/docs_lint.py - do not edit by hand. Run: python tools/docs_lint.py --fix -->

# Design Documents Index

> Registry of design documents for {{ProjectName}}. This file is generated from the
> frontmatter of `docs/design-docs/*.md`. To add a design doc: create the file from
> `design-doc.md.tpl`, fill in frontmatter, then run `python tools/docs_lint.py --fix`.

| Document | Status | Owner | Ticket | Updated | Title |
|----------|--------|-------|--------|---------|-------|
| <!-- generated rows --> | | | | | |
