#!/usr/bin/env python3
"""Fleet engineering docs linter + index generator.

Commit as {repo}/tools/docs_lint.py. Zero third-party dependencies (stdlib only),
so it runs in any CI image with Python 3.8+.

Modes:
  python tools/docs_lint.py --fix            regenerate all GENERATED files
  python tools/docs_lint.py --check          CI gate: validate + fail if anything is stale/broken
  python tools/docs_lint.py --check --strict-stale   also fail (not warn) on staleness findings

Every failure message is self-healing: it names the file, the rule, and the exact fix.
"""
import argparse
import re
import sys
from datetime import date, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

GENERATED_BANNER = (
    "<!-- GENERATED by tools/docs_lint.py - do not edit by hand. "
    "Run: python tools/docs_lint.py --fix -->"
)

STALE_PLAN_DAYS = 21
STALE_P1_DEBT_DAYS = 30

ALLOWED_STATUS = {
    "product-spec": {"Draft", "In Review", "Approved", "Superseded", "Archived"},
    "design-doc": {"Draft", "In Review", "Approved", "Superseded", "Archived"},
    "exec-plan": {"Draft", "In Review", "Active", "Completed", "Superseded", "Archived"},
    "tech-debt": {"Active", "Archived"},
    "quality-area": {"Active"},
}
REQUIRED_FIELDS = ["type", "title", "status", "owner", "ticket", "created", "updated"]

errors = []
warnings = []


def err(msg):
    errors.append(msg)


def warn(msg):
    warnings.append(msg)


# ---------------------------------------------------------------- frontmatter
def parse_frontmatter(path):
    """Minimal YAML-subset parser: 'key: value', 'key:' + '  - item' lists, and one
    nested level for 'claims:' with 'code:'/'docs:' lists. Returns (dict, body)."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return None, text
    end = text.find("\n---", 3)
    if end < 0:
        return None, text
    block, body = text[3:end], text[end + 4:]
    data = {}
    stack = [(0, data)]
    for raw in block.splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip())
        line = raw.strip()
        while stack and indent < stack[-1][0]:
            stack.pop()
        container = stack[-1][1] if stack else data
        if line.startswith("- "):
            if isinstance(container, list):
                container.append(line[2:].strip().strip('"').strip("'"))
            continue
        if ":" in line:
            key, _, val = line.partition(":")
            key, val = key.strip(), val.strip().strip('"').strip("'")
            if val in ("", "[]"):
                child = [] if val == "[]" else None
                if child is None:
                    # could be a dict (claims:) or a list; decide lazily: use dict for
                    # known nested keys, list otherwise
                    child = {} if key == "claims" else []
                container[key] = child
                stack.append((indent + 2, child))
            else:
                container[key] = val
    return data, body


def parse_date(value):
    try:
        return datetime.strptime(str(value), "%Y-%m-%d").date()
    except (TypeError, ValueError):
        return None


def collect(dirpath, doc_type):
    out = []
    if not dirpath.is_dir():
        return out
    for p in sorted(dirpath.glob("*.md")):
        if p.name == "index.md":
            continue
        fm, _ = parse_frontmatter(p)
        if fm is None:
            err(f"{rel(p)}: missing YAML frontmatter. Fix: add the frontmatter block from "
                f"the {doc_type} template in .claude/skills/fleet-engineering/templates/.")
            continue
        fm["_path"] = p
        out.append(fm)
    return out


def rel(p):
    return p.relative_to(ROOT).as_posix() if isinstance(p, Path) else p


# ---------------------------------------------------------------- validation
def validate_doc(fm, expected_type):
    p = rel(fm["_path"])
    for field in REQUIRED_FIELDS:
        if not fm.get(field) or "INSTRUCTION" in str(fm.get(field, "")):
            err(f"{p}: frontmatter field '{field}' is missing or unfilled. "
                f"Fix: set a real value (see references/docs-automation.md for the schema).")
    if fm.get("type") and fm["type"] != expected_type:
        err(f"{p}: type is '{fm['type']}' but this directory holds '{expected_type}' docs. "
            f"Fix: correct the type or move the file.")
    status = fm.get("status")
    if status and status not in ALLOWED_STATUS.get(expected_type, set()):
        allowed = ", ".join(sorted(ALLOWED_STATUS[expected_type]))
        err(f"{p}: status '{status}' is not valid for {expected_type} (allowed: {allowed}).")


def validate_links(md_path):
    fm, body = parse_frontmatter(md_path)
    for match in re.finditer(r"\]\(([^)#\s]+\.md)(#[^)]*)?\)", body or ""):
        target = match.group(1)
        if target.startswith(("http://", "https://")):
            continue
        resolved = (md_path.parent / target).resolve()
        if not resolved.exists():
            err(f"{rel(md_path)}: broken link '{target}'. "
                f"Fix: correct the path or remove the link.")


# ---------------------------------------------------------------- claims
def glob_prefix(pattern):
    pattern = pattern.replace("\\", "/").lstrip("./")
    for i, ch in enumerate(pattern):
        if ch in "*?[":
            return pattern[:i].rstrip("/")
    return pattern.rstrip("/")


def claims_of(plan):
    claims = plan.get("claims") or {}
    if not isinstance(claims, dict):
        return []
    pats = []
    for key in ("code", "docs"):
        val = claims.get(key) or []
        if isinstance(val, list):
            pats.extend(str(v) for v in val if v and "INSTRUCTION" not in str(v))
    return pats


def check_claim_overlaps(active_plans):
    for i, a in enumerate(active_plans):
        for b in active_plans[i + 1:]:
            hits = []
            for pa in claims_of(a):
                for pb in claims_of(b):
                    fa, fb = glob_prefix(pa), glob_prefix(pb)
                    if fa and fb and (fa.startswith(fb) or fb.startswith(fa)):
                        hits.append(f"'{pa}' vs '{pb}'")
            if hits:
                warn(f"CLAIM OVERLAP between {rel(a['_path'])} and {rel(b['_path'])}: "
                     f"{'; '.join(hits)}. Fix: the two plan owners must arbitrate "
                     f"(re-scope, sequence, or record accepted risk in both plans' "
                     f"Decisions Log). See references/collaboration-controls.md.")


# ---------------------------------------------------------------- generation
def md_link(p, base):
    return p.relative_to(base).as_posix()


def gen_table(docs, base, extra_cols=()):
    lines = ["| Document | Status | Owner | Ticket | Updated | Title |",
             "|----------|--------|-------|--------|---------|-------|"]
    for fm in sorted(docs, key=lambda d: str(d.get("ticket"))):
        link = md_link(fm["_path"], base)
        lines.append(
            f"| [{fm['_path'].name}](./{link}) | {fm.get('status','?')} | "
            f"{fm.get('owner','?')} | {fm.get('ticket','?')} | "
            f"{fm.get('updated','?')} | {fm.get('title','?')} |")
    if len(lines) == 2:
        lines.append("| (none yet) | | | | | |")
    return "\n".join(lines)


def generate_all():
    """Return {path: content} for every generated file."""
    out = {}
    specs = collect(DOCS / "product-specs", "product-spec")
    designs = collect(DOCS / "design-docs", "design-doc")
    active = collect(DOCS / "exec-plans" / "active", "exec-plan")
    completed = collect(DOCS / "exec-plans" / "completed", "exec-plan")
    debt = collect(DOCS / "tech-debt", "tech-debt")
    quality = collect(DOCS / "quality", "quality-area")

    out[DOCS / "product-specs" / "index.md"] = "\n\n".join([
        GENERATED_BANNER, "# Product Specifications Index",
        "> Generated from frontmatter of `docs/product-specs/*.md`. To add a spec: create "
        "the file from the template, fill in frontmatter, run `python tools/docs_lint.py --fix`.",
        gen_table(specs, DOCS / "product-specs")]) + "\n"

    out[DOCS / "design-docs" / "index.md"] = "\n\n".join([
        GENERATED_BANNER, "# Design Documents Index",
        "> Generated from frontmatter of `docs/design-docs/*.md`.",
        gen_table(designs, DOCS / "design-docs")]) + "\n"

    out[DOCS / "exec-plans" / "index.md"] = "\n\n".join([
        GENERATED_BANNER, "# Execution Plans Index",
        "> Generated. Active plans' `claims` are live coordination locks.",
        "## Active", gen_table(active, DOCS / "exec-plans"),
        "## Completed", gen_table(completed, DOCS / "exec-plans")]) + "\n"

    debt_active = [d for d in debt if not d.get("resolved")]
    debt_resolved = [d for d in debt if d.get("resolved")]
    out[DOCS / "tech-debt" / "index.md"] = "\n\n".join([
        GENERATED_BANNER, "# Tech Debt Index",
        "> Generated from `docs/tech-debt/TD-*.md`. One file per entry.",
        "## Active", gen_table(debt_active, DOCS / "tech-debt"),
        "## Resolved", gen_table(debt_resolved, DOCS / "tech-debt")]) + "\n"

    qlines = ["| Area | Score | Reviewed | Owner | Detail |",
              "|------|-------|----------|-------|--------|"]
    for fm in sorted(quality, key=lambda d: str(d.get("area"))):
        link = md_link(fm["_path"], DOCS)
        qlines.append(f"| {fm.get('area','?')} | {fm.get('score','?')} | "
                      f"{fm.get('reviewed','?')} | {fm.get('owner','?')} | "
                      f"[{fm['_path'].name}](./{link}) |")
    if len(qlines) == 2:
        qlines.append("| (no areas scored yet) | | | | |")
    out[DOCS / "QUALITY_SCORE.md"] = "\n\n".join([
        GENERATED_BANNER, "# Quality Score Dashboard",
        "> Generated from `docs/quality/*.md`. Edit those files, not this one.\n"
        "> Scoring: A well-tested+documented / B minor gaps / C needs cleanup / "
        "D significant debt / F broken.",
        "\n".join(qlines)]) + "\n"

    return out, dict(specs=specs, designs=designs, active=active,
                     completed=completed, debt=debt, quality=quality)


# ---------------------------------------------------------------- modes
def run_fix():
    generated, _ = generate_all()
    for path, content in generated.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"regenerated {rel(path)}")
    return 0


def run_check(strict_stale):
    generated, docs = generate_all()
    today = date.today()

    # 1. generated files fresh
    for path, content in generated.items():
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual != content:
            err(f"{rel(path)}: GENERATED file is stale or hand-edited. "
                f"Fix: run 'python tools/docs_lint.py --fix' and commit the result.")

    # 2. frontmatter validity
    for key, expected in (("specs", "product-spec"), ("designs", "design-doc"),
                          ("active", "exec-plan"), ("completed", "exec-plan"),
                          ("debt", "tech-debt"), ("quality", "quality-area")):
        for fm in docs[key]:
            validate_doc(fm, expected)

    # 3. lifecycle/directory consistency
    for fm in docs["completed"]:
        if fm.get("status") != "Completed":
            err(f"{rel(fm['_path'])}: lives in completed/ but status is "
                f"'{fm.get('status')}'. Fix: set status: Completed.")
    for fm in docs["active"]:
        if fm.get("status") == "Completed":
            err(f"{rel(fm['_path'])}: status Completed but still in active/. "
                f"Fix: git mv it to docs/exec-plans/completed/.")

    # 4. duplicate tickets among plans
    seen = {}
    for fm in docs["active"] + docs["completed"]:
        t = fm.get("ticket")
        if t and t in seen:
            err(f"ticket '{t}' appears in both {rel(seen[t])} and {rel(fm['_path'])}. "
                f"Fix: one plan per ticket; merge or re-ticket.")
        seen[t] = fm["_path"]

    # 5. claims overlap among active plans
    check_claim_overlaps([f for f in docs["active"] if f.get("status") == "Active"])

    # 6. staleness
    for fm in docs["active"]:
        upd = parse_date(fm.get("updated"))
        if fm.get("status") == "Active" and upd and (today - upd).days > STALE_PLAN_DAYS:
            warn(f"{rel(fm['_path'])}: Active plan not updated in {(today - upd).days} days "
                 f"(limit {STALE_PLAN_DAYS}). Fix: update it, complete it, or archive it; "
                 f"stale plans hold claims locks the team must respect.")
    for fm in docs["debt"]:
        crt = parse_date(fm.get("created"))
        if (fm.get("priority") == "P1" and not fm.get("resolved") and crt
                and (today - crt).days > STALE_P1_DEBT_DAYS):
            warn(f"{rel(fm['_path'])}: P1 debt open {(today - crt).days} days "
                 f"(limit {STALE_P1_DEBT_DAYS}). Fix: schedule it or justify a downgrade.")

    # 7. links
    for sub in ("product-specs", "design-docs", "exec-plans/active",
                "exec-plans/completed", "tech-debt", "quality"):
        d = DOCS / sub
        if d.is_dir():
            for p in d.glob("*.md"):
                if p.name != "index.md":
                    validate_links(p)

    for w in warnings:
        print(f"WARN: {w}\n")
    for e in errors:
        print(f"ERROR: {e}\n")
    failed = bool(errors) or (strict_stale and bool(warnings))
    print(f"docs_lint: {len(errors)} error(s), {len(warnings)} warning(s)")
    return 1 if failed else 0


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--fix", action="store_true", help="regenerate GENERATED files")
    mode.add_argument("--check", action="store_true", help="validate; non-zero exit on failure")
    ap.add_argument("--strict-stale", action="store_true",
                    help="treat staleness/overlap warnings as failures (scheduled sweeps)")
    args = ap.parse_args()
    return run_fix() if args.fix else run_check(args.strict_stale)


if __name__ == "__main__":
    sys.exit(main())
