<!-- GENERATED by tools/docs_lint.py - do not edit by hand. Run: python tools/docs_lint.py --fix -->

# Product Specifications Index

> Registry of product specs for {{ProjectName}}. This file is generated from the
> frontmatter of `docs/product-specs/*.md`. To add a spec: create the file from
> `product-spec.md.tpl`, fill in frontmatter, then run `python tools/docs_lint.py --fix`.

| Spec | Status | Owner | Ticket | Updated | Title |
|------|--------|-------|--------|---------|-------|
| <!-- generated rows --> | | | | | |
